[package]
name = "orzcc"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.19.9"

[dependencies]
clap = "=4.2.0"
thiserror = "=1.0.40"
hexponent = {version = "0.2", default-features = false}
lalrpop-util = { version = "0.19.9", features = ["lexer"] }