use std::collections::HashMap;
use std::fmt;

use crate::ir::block::Block;
use crate::ir::utils::{IdAllocator, NameAllocator};
use crate::ir::value::{Value, ValueData};

use super::block::BlockData;
use super::constant::{Constant, ConstantData};
use super::function::{Function, FunctionData};
use super::global::{Global, GlobalData};
use super::inst::{Inst, InstData};
use super::ty::Type;
use super::utils::InstCommenter;

/// Module of IR.
///
/// Module contains the entity information of each references.
/// The information in a module can be used to (re-)initialize a builder
///
/// A module does not represent any special structure by itself though
/// implicitly the data-flow-graph is stored. The sequence of instructions
/// and blocks are stored inside the corresponding function. Special
/// graph or other representations should be introduced by independent
/// passes and even the implicit dfg should not be used directly from
/// the module.
///
/// Though being SSA form, the module does not store explicit the def-use chains.
/// The use-def chain can be queried from instruction by the `value` because of SSA.
///
/// If execution is needed, just use the sequential representation in the
/// module (control-flow relation might needs to be analyzed during execution).
///
/// All the indexer (Value, Inst, Block, etc) can be converted to
/// represent a value. and the actual data is stored in the corresponding maps.
///
/// Value name assignment needs to be done before dumping the ir.
pub struct Module {
    /// The value and corresponding data in the module.
    pub values: HashMap<Value, ValueData>,

    /// The instructions
    pub insts: HashMap<Inst, InstData>,

    /// The blocks
    pub blocks: HashMap<Block, BlockData>,

    /// The constants
    pub constants: HashMap<Constant, ConstantData>,

    /// The globals
    pub globals: HashMap<Global, GlobalData>,

    /// The functions
    pub functions: HashMap<Function, FunctionData>,

    /// Identified types
    pub identified_types: HashMap<String, Type>,

    /// The id allocator
    pub(super) id_allocator: IdAllocator,

    /// The name allocator for values
    pub(super) value_name_allocator: NameAllocator<Value>,

    /// The name allocator for blocks
    pub(super) block_name_allocator: NameAllocator<Block>,

    /// Instruction commenter
    pub(super) inst_commenter: InstCommenter,
}

impl Module {
    /// Allocate index as a value
    pub fn allocate_id(&mut self) -> Value {
        Value::new(self.id_allocator.allocate())
    }

    /// Assign a custom name to value.
    ///
    /// This can be used in optimization passes.
    pub fn assign_value_name(&mut self, value: &Value, name: String) -> Result<(), String> {
        self.value_name_allocator.assign(value, name)
    }

    /// Assign a custom name to block.
    ///
    /// This can be used in some control-flow-related optimizations.
    pub fn assign_block_name(&mut self, block: &Block, name: String) -> Result<(), String> {
        self.block_name_allocator.assign(block, name)
    }

    /// Comment at instruction.
    ///
    /// This can be used to put some debug/necessary information to IR when dumping.
    pub fn comment_at_inst(&mut self, inst: &Inst, comment: String) {
        self.inst_commenter.comment(inst, comment)
    }
}

impl fmt::Display for Module {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "# Generated by ORZCC")
    }
}
